spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch_ex?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatement=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
#        format_sql: true

# META-TABLE 자동생성 설정
  batch:
    initialize-schema: always

